"use strict";
const { assert, createRegistry, createHost, createStorage, context } = require("./m69-test-helpers.cjs");
const { createUiEditorRuntime, RUNTIME_ERROR_CODES } = require("../src/index.cjs");
let storage=createStorage(), host=createHost(); let rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:storage,targetContext:context});
rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:1},changeId:"c1",createdAt:"n",source:"t"}); rt.applyChange({elementId:"demo.card.title",operation:"move",payload:{x:2},changeId:"c2",createdAt:"n",source:"t"}); rt.saveLayout(); assert.equal(rt.resetElementToDefaults("demo.card").ok,true); assert.equal(host.dump()["demo.card"],undefined); assert.equal(host.dump()["demo.card.title"].x,2); assert.equal(storage.readResult(context).entries.some(e=>e.elementId==="demo.card"),false); assert.equal(storage.readResult(context).entries.some(e=>e.elementId==="demo.card.title"),true); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:3},changeId:"c3",createdAt:"n",source:"t"}); rt.discardElementChanges("demo.card"); assert.equal(host.dump()["demo.card"],undefined);
assert.equal(rt.resetLayoutToDefaults().ok,true); assert.deepEqual(storage.readResult(context).entries,[]); assert.equal(rt.getSessionStatus().changedCount,0);
storage=createStorage(); host=createHost(); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:storage,targetContext:context}); rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:7},changeId:"c4",createdAt:"n",source:"t"}); rt.saveLayout(); host.fail.clear="demo.card"; const before=JSON.stringify(host.dump()); const res=rt.resetLayoutToDefaults(); assert.equal(res.code,RUNTIME_ERROR_CODES.HOST_CLEAR_FAILED); assert.equal(JSON.stringify(host.dump()),before); assert.equal(storage.readResult(context).entries[0].x,7);
storage=createStorage(); storage.clear=function(){return {ok:false,reason:"no"};}; host=createHost(); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:storage,targetContext:context}); rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:8},changeId:"c5",createdAt:"n",source:"t"}); rt.saveLayout(); assert.equal(rt.resetLayoutToDefaults().code,RUNTIME_ERROR_CODES.STORAGE_CLEAR_FAILED); assert.equal(host.dump()["demo.card"].x,8);
console.log("m69 reset runtime ok");
