"use strict";
const { assert, createRegistry, createHost, createStorage, context } = require("./m69-test-helpers.cjs");
const { createUiEditorRuntime, RUNTIME_ERROR_CODES } = require("../src/index.cjs");
let storage=createStorage(); let host=createHost(); let rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:storage,targetContext:context});
rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:10},changeId:"c1",createdAt:"n",source:"test"}); assert.equal(rt.saveLayout().status.changedCount,0); assert.equal(storage.readResult(context).entries[0].x,10);
host=createHost(); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:storage,targetContext:context}); assert.equal(rt.loadLayout().ok,true); assert.equal(host.dump()["demo.card"].x,10); assert.equal(rt.getSessionStatus().changedCount,0);
const other={...context,layoutProfileId:"alternate"}; storage.write(other,[{elementId:"demo.card",x:99}]); assert.equal(storage.readResult(context).entries[0].x,10); assert.equal(storage.readResult(other).entries[0].x,99);
const unavailable=createStorage(); unavailable.available=false; rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:createHost(),layoutStorage:unavailable,targetContext:context}); rt.beginSession(); assert.equal(rt.saveLayout().code,RUNTIME_ERROR_CODES.STORAGE_UNAVAILABLE);
const volatile=createStorage(); volatile.persistent=false; rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:createHost(),layoutStorage:volatile,targetContext:context}); rt.beginSession(); assert.equal(rt.saveLayout().code,RUNTIME_ERROR_CODES.STORAGE_NOT_PERSISTENT);
const bad=createStorage(); bad.write(context,[{elementId:"demo.card",x:7}]); bad.setStaleAfterWrite(true); host=createHost(); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:bad,targetContext:context}); rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:1},changeId:"c",createdAt:"n",source:"t"}); const saveFail=rt.saveLayout(); assert.equal(saveFail.code,RUNTIME_ERROR_CODES.STORAGE_VERIFY_FAILED); assert.equal(saveFail.rollbackComplete,true); assert.equal(bad.readResult(context).entries[0].x,7); assert.equal(rt.getSessionStatus().changedCount,1);
const loadStorage=createStorage(); loadStorage.write(context,[{elementId:"demo.card",x:5},{elementId:"missing",x:6}]); host=createHost({"demo.card":{elementId:"demo.card",x:10}}); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:loadStorage,targetContext:context}); rt.beginSession(); const loadFail=rt.loadLayout(); assert.equal(loadFail.code,RUNTIME_ERROR_CODES.UNKNOWN_ELEMENT); assert.equal(host.dump()["demo.card"].x,10); assert.equal(rt.getSessionStatus().changedCount,0);
loadStorage.write(context,[{elementId:"demo.card",x:5}]); host=createHost({"demo.card":{elementId:"demo.card",x:10},"demo.table":{elementId:"demo.table",width:20}}); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:loadStorage,targetContext:context}); rt.beginSession(); assert.equal(rt.loadLayout().ok,true); assert.equal(host.dump()["demo.card"].x,5); assert.equal(host.dump()["demo.table"],undefined); assert.deepEqual(rt.getSessionStatus().changedElementIds,[]);
loadStorage.write(context,[{elementId:"demo.card",x:1},{elementId:"demo.table",width:30}]); host=createHost({"demo.card":{elementId:"demo.card",x:10},"demo.table":{elementId:"demo.table",width:20}}); host.fail.apply="demo.table"; rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:loadStorage,targetContext:context}); rt.beginSession(); const hostFail=rt.loadLayout(); assert.equal(hostFail.code,RUNTIME_ERROR_CODES.HOST_APPLY_FAILED); assert.equal(hostFail.rollbackComplete,true); assert.equal(host.dump()["demo.card"].x,10); assert.equal(host.dump()["demo.table"].width,20); assert.equal(rt.getSessionStatus().changedCount,0);

const invalidOpsStorage=createStorage(); invalidOpsStorage.write(context,[{elementId:"demo.table",x:20}]); host=createHost({"demo.table":{elementId:"demo.table",width:10}}); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:invalidOpsStorage,targetContext:context}); assert.equal(rt.beginSession().ok,true); const resizeOnlyMoveFail=rt.loadLayout(); assert.equal(resizeOnlyMoveFail.code,RUNTIME_ERROR_CODES.OPERATION_NOT_ALLOWED); assert.equal(host.dump()["demo.table"].width,10); assert.equal(rt.getSessionStatus().changedCount,0);
invalidOpsStorage.write(context,[{elementId:"demo.card",width:300}]); host=createHost({"demo.card":{elementId:"demo.card",x:10}}); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:invalidOpsStorage,targetContext:context}); rt.beginSession(); const moveOnlyResizeFail=rt.loadLayout(); assert.equal(moveOnlyResizeFail.code,RUNTIME_ERROR_CODES.OPERATION_NOT_ALLOWED); assert.equal(host.dump()["demo.card"].x,10); assert.equal(rt.getSessionStatus().changedCount,0);
invalidOpsStorage.write(context,[{elementId:"demo.table",width:300,x:20}]); host=createHost({"demo.table":{elementId:"demo.table",width:10}}); rt=createUiEditorRuntime({registry:createRegistry(),hostAdapter:host,layoutStorage:invalidOpsStorage,targetContext:context}); rt.beginSession(); const mixedFail=rt.loadLayout(); assert.equal(mixedFail.code,RUNTIME_ERROR_CODES.OPERATION_NOT_ALLOWED); assert.equal(host.dump()["demo.table"].width,10); assert.equal(rt.getSessionStatus().changedCount,0);
function createMutableRegistry(allowMove){ const base=createRegistry(); return { listElements(){ return base.listElements(); }, getElementById(id){ const element=base.getElementById(id); if(id==="demo.card" && element) element.allowedOps=allowMove.value?["move"]:[]; return element; } }; }
const allowMove={value:true}; storage=createStorage(); host=createHost(); rt=createUiEditorRuntime({registry:createMutableRegistry(allowMove),hostAdapter:host,layoutStorage:storage,targetContext:context}); rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:44},changeId:"rv",createdAt:"n",source:"t"}); allowMove.value=false; const callsBefore=host.calls.filter(call=>call[0]==="apply").length; assert.equal(rt.reapplyCurrentLayoutState().code,RUNTIME_ERROR_CODES.OPERATION_NOT_ALLOWED); assert.equal(host.calls.filter(call=>call[0]==="apply").length,callsBefore); assert.equal(storage.calls.filter(call=>call[0]==="write").length,0);
allowMove.value=true; storage=createStorage(); host=createHost(); rt=createUiEditorRuntime({registry:createMutableRegistry(allowMove),hostAdapter:host,layoutStorage:storage,targetContext:context}); rt.beginSession(); rt.applyChange({elementId:"demo.card",operation:"move",payload:{x:55},changeId:"sv",createdAt:"n",source:"t"}); allowMove.value=false; const writesBefore=storage.calls.filter(call=>call[0]==="write").length; const saveInvalid=rt.saveLayout(); assert.equal(saveInvalid.code,RUNTIME_ERROR_CODES.OPERATION_NOT_ALLOWED); assert.equal(storage.calls.filter(call=>call[0]==="write").length,writesBefore); assert.equal(rt.getSessionStatus().changedCount,1);
console.log("m69 layout persistence ok");
