"use strict";
const { assert, createDoc, memoryStorage } = require("./m72-reference-test-helpers.cjs");
const { createReferenceApp } = require("../examples/browser-reference/reference-app.cjs");
const doc = createDoc();
const cardBeforeTransform = "rotate(1deg)";
const app = createReferenceApp({ documentAdapter: doc, windowAdapter: { localStorage: memoryStorage(), addEventListener(){}, removeEventListener(){} }, root: doc.getElementById("reference-app") });
const card = doc.getElementById("reference-demo-card");
const stage = doc.getElementById("reference-stage");
const panelMount = doc.getElementById("reference-panel");
const profile = doc.getElementById("reference-profile");
const tool = doc.getElementById("reference-show-layout");
card.style.transform = cardBeforeTransform;
app.runtime.applyChange({ elementId: "demo.card", operation: "move", payload: { x: 5 }, source: "test" });
assert.equal(app.runtime.resetElementToDefaults("demo.card").ok, true);
assert.equal(card.style.transform, cardBeforeTransform);
app.selectionHost.select("demo.card");
assert.ok(stage.children.some((child) => child.className === "ui-editor-browser-overlay"));
assert.ok(panelMount.children.length > 0);
assert.equal(card.listenerCount("click"), 1);
assert.equal(stage.listenerCount("click"), 1);
assert.equal(profile.listenerCount("change"), 1);
assert.equal(tool.listenerCount("click"), 1);
app.selectionHost.clear();
const statusBeforeDestroy = doc.getElementById("reference-status").innerHTML;
app.destroy();
assert.equal(panelMount.children.length, 0);
assert.equal(stage.children.some((child) => child.className === "ui-editor-browser-overlay"), false);
assert.equal(card.listenerCount("click"), 0);
assert.equal(stage.listenerCount("click"), 0);
assert.equal(profile.listenerCount("change"), 0);
assert.equal(tool.listenerCount("click"), 0);
card.dispatch("click");
assert.equal(app.selectionHost.getSelection().selectedElementId, null);
assert.equal(doc.getElementById("reference-status").innerHTML, statusBeforeDestroy);
app.controller.refresh();
app.selectionHost.clear();
assert.equal(doc.getElementById("reference-status").innerHTML, statusBeforeDestroy);
app.destroy();
assert.equal(app.elementRefs.listIds().length, 0);
assert.equal(app.bridge.updateOverlay().code, "BRIDGE_DESTROYED");
assert.equal(card.style.transform, cardBeforeTransform);
console.log("m72 reference lifecycle ok");
