#!/usr/bin/env node
"use strict";
const assert = require("node:assert/strict");
const { createHoverOverlay, createSelectedOverlay } = require("../../src/index.cjs");
function events(){ const entries=[]; return { addEventListener(type,fn,capture){ entries.push({type,fn,capture}); }, removeEventListener(type,fn,capture){ const i=entries.findIndex(e=>e.type===type&&e.fn===fn&&e.capture===capture); if(i>=0) entries.splice(i,1); }, count(type){ return entries.filter(e=>!type||e.type===type).length; }, fire(type){ entries.filter(e=>e.type===type).slice().forEach(e=>e.fn({type})); } }; }
function el(tag){ return { tag, nodeType:1, style:{}, children:[], parentNode:null, textContent:"", ownerDocument:null, setAttribute(k,v){this[k]=v;}, appendChild(c){c.parentNode=this;this.children.push(c);}, removeChild(c){this.children=this.children.filter(x=>x!==c);c.parentNode=null;}, contains(t){return t===this||this.children.includes(t);}, getBoundingClientRect(){return this.rect||{left:1,top:2,width:30,height:40};} }; }
function doc(){ const d=Object.assign(events(),{ body:el('body'), defaultView:events(), createElement(tag){ const x=el(tag); x.ownerDocument=d; return x; } }); d.body.ownerDocument=d; return d; }
const document = doc(); const target = el('target'); target.ownerDocument=document; target.rect={left:10,top:20,width:100,height:50}; const before=JSON.stringify(target.style);
const hover=createHoverOverlay({showLabel:true}); hover.show({ref:target,target:{elementId:'a',label:'Alpha'},document}); hover.show({ref:target,target:{elementId:'a',label:'Alpha'},document});
assert.equal(document.body.children.length,1); assert.equal(document.count('scroll'),1); assert.equal(document.defaultView.count('resize'),1); assert.equal(hover.getElement().style.pointerEvents,'none'); assert.equal(hover.getElement().style.position,'fixed'); assert.equal(hover.getElement().style.left,'10px'); assert.equal(JSON.stringify(target.style),before); target.rect.left=15; document.fire('scroll'); assert.equal(hover.getElement().style.left,'15px'); target.rect.top=25; document.defaultView.fire('resize'); assert.equal(hover.getElement().style.top,'25px'); hover.clear(); assert.equal(hover.isVisible(),false); assert.equal(document.count('scroll'),0); assert.equal(document.defaultView.count('resize'),0); hover.destroy(); assert.equal(document.body.children.length,0);
const selected=createSelectedOverlay({showLabel:true}); selected.show({ref:target,target:{elementId:'b',label:'Beta'},document}); assert.match(selected.getElement().children[0].textContent,/Selected: Beta · b/); selected.show({ref:target,target:{elementId:'b',label:'Beta'},document}); assert.equal(document.count('scroll'),1); assert.equal(document.defaultView.count('resize'),1); selected.destroy(); assert.equal(document.count('scroll'),0); assert.equal(document.defaultView.count('resize'),0);
console.log('m58 selection overlay tests passed');
