#!/usr/bin/env node
"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { createSelectionController, resolveSelectionTarget } = require("../../src/index.cjs");
function emitter(){ const entries=[]; return { addEventListener(t,f,o){ entries.push({t,f,o});}, removeEventListener(t,f,o){ const i=entries.findIndex(e=>e.t===t&&e.f===f&&e.o===o); if(i>=0) entries.splice(i,1);}, count(t){return entries.filter(e=>!t||e.t===t).length}, fire(t,e={}){ entries.filter(x=>x.t===t).slice().forEach(x=>x.f(Object.assign({type:t,target:this},e))); } }; }
function elem(id, rect, parent){ const e=Object.assign(emitter(),{ id,nodeType:1,style:{},children:[],parentNode:parent||null,ownerDocument:null,rect:rect||{left:0,top:0,width:10,height:10},contains(t){return t===this||this.children.includes(t);},getBoundingClientRect(){return this.rect;},appendChild(c){c.parentNode=this;this.children.push(c);},removeChild(c){this.children=this.children.filter(x=>x!==c);c.parentNode=null;},setAttribute(k,v){this[k]=v;}}); if(parent) parent.children.push(e); return e; }
function doc(){ const body=elem('body'); const d=Object.assign(emitter(),{body,defaultView:emitter(),createElement(tag){const x=elem(tag); x.ownerDocument=d; return x;}}); body.ownerDocument=d; return d; }
function host(root, refs){ let selected=null; const calls=[]; return { listSelectableTargets(){return [{elementId:'a',label:'A'},{elementId:'b',label:'B',parentId:'a'},{elementId:'c',selectable:false},{elementId:'missing'}]}, getElementRef:id=>refs[id]||null, getSelectedElementId:()=>selected, selectElement:id=>{calls.push(id); selected=id;}, getInteractionRoot:()=>root, isExcludedTarget:t=>t&&t.id==='excluded', onSelection:s=>calls.push('sel:'+s.elementId), calls, setSelected:id=>{selected=id} }; }
(async()=>{
 const document=doc(), root=elem('root'), a=elem('a',{left:0,top:0,width:100,height:100}), b=elem('b',{left:5,top:5,width:20,height:20},a), c=elem('c'); [root,a,b,c].forEach(x=>x.ownerDocument=document); const refs={a,b,c}; const h=host(root,refs);
 assert.equal(root.count(),0); const controller=createSelectionController({host:h,document,window:document.defaultView}); assert.equal(root.count(),0);
 controller.start(); const count=root.count(); controller.start(); assert.equal(root.count(),count); assert.equal(controller.isActive(),true);
 root.fire('pointermove',{target:b}); assert.equal(controller.getState().hoveredElementId,'b');
 root.fire('pointermove',{target:{id:'excluded',nodeType:1,contains(){return false},getBoundingClientRect(){return {}}}}); assert.equal(controller.getState().hoveredElementId,null);
 root.fire('pointermove',{target:b}); root.fire('click',{target:b,preventDefault(){this.prevented=true},stopPropagation(){this.stopped=true},stopImmediatePropagation(){this.immediate=true}}); await new Promise(r=>setTimeout(r,0)); assert.deepEqual(h.calls.slice(0,2),['b','sel:b']); assert.equal(controller.isActive(),true); assert.equal(controller.getState().selectedElementId,'b'); assert.equal(controller.getState().hoveredElementId,null);
 h.setSelected('a'); controller.syncWithSelection(); assert.equal(document.count('scroll'),2); assert.equal(document.defaultView.count('resize'),2); controller.syncWithSelection(); assert.equal(document.count('scroll'),2); assert.equal(document.defaultView.count('resize'),2); assert.equal(controller.getState().selectedElementId,'a'); root.fire('keydown',{key:'Escape'}); assert.equal(controller.isActive(),false); assert.equal(root.count(),0); assert.equal(document.count('scroll'),1); assert.equal(document.defaultView.count('resize'),1); a.rect.left=33; document.fire('scroll'); assert.equal(document.body.children[1].style.left,'33px'); a.rect.top=44; document.defaultView.fire('resize'); assert.equal(document.body.children[1].style.top,'44px'); h.setSelected(null); controller.syncWithSelection(); assert.equal(document.count('scroll'),0); assert.equal(document.defaultView.count('resize'),0);
 controller.start(); controller.stop(); controller.stop(); assert.equal(root.count(),0); h.setSelected('a'); controller.syncWithSelection(); assert.equal(document.count('scroll'),1); controller.destroy(); controller.destroy(); assert.equal(document.count('scroll'),0); assert.equal(document.defaultView.count('resize'),0); controller.start(); assert.equal(root.count(),0);

 const unhandled=[]; const onUnhandled=(reason)=>unhandled.push(reason); process.on('unhandledRejection', onUnhandled);
 const root2=elem('root2'), x=elem('x',{left:1,top:1,width:10,height:10}); x.ownerDocument=document;
 const failingHost={ listSelectableTargets(){return [{elementId:'x'}]}, getElementRef:id=>id==='x'?x:null, getSelectedElementId:()=>null, selectElement:()=>Promise.reject(new Error('select failed')), getInteractionRoot:()=>root2, onError(){throw new Error('host onError failed')}, onStateChange(){throw new Error('state failed')} };
 const failingController=createSelectionController({host:failingHost,document,window:document.defaultView,onError(){throw new Error('option onError failed')}});
 failingController.start(); root2.fire('click',{target:x,preventDefault(){},stopPropagation(){},stopImmediatePropagation(){}}); await new Promise(r=>setTimeout(r,0)); await new Promise(r=>setTimeout(r,0));
 assert.equal(unhandled.length,0); assert.equal(failingController.isActive(),true); failingController.stop(); assert.equal(failingController.isActive(),false); failingController.destroy(); process.removeListener('unhandledRejection', onUnhandled);
 const match=resolveSelectionTarget({eventTarget:b,targets:[{elementId:'a'},{elementId:'b',parentId:'a'},{elementId:'c',selectable:false},{elementId:'missing'}],getElementRef:id=>refs[id]||null}); assert.equal(match.elementId,'b');
 const source=fs.readFileSync(path.join(__dirname,'../../src/selection/targetResolver.js'),'utf8')+fs.readFileSync(path.join(__dirname,'../../src/selection/selectionController.js'),'utf8'); [/querySelector/,/getElementById/,/getElementsBy/,/closest/,/matches/,/MutationObserver/,/elementFromPoint/,/elementsFromPoint/,/LayoutStore/,/electron|ipc/i].forEach(re=>assert.equal(re.test(source),false,String(re)));
 console.log('m58 selection runtime tests passed');
})();
