<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>ReferenceTargetApp</RootNamespace>
    <AssemblyName>ReferenceTargetApp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ReferenceTargetApp.Domain/ReferenceTargetApp.Domain.csproj" />
    <ProjectReference Include="../ReferenceTargetApp.EditorIntegration/ReferenceTargetApp.EditorIntegration.csproj" />
    <ProjectReference Include="../ReferenceTargetApp.Infrastructure/ReferenceTargetApp.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ReferenceTargetApp.Tests" />
  </ItemGroup>
</Project>
