<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>UiEditorManager</AssemblyName>
    <Product>UI-Editor Manager</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UiEditorKit.Manager.Domain/UiEditorKit.Manager.Domain.csproj" />
    <ProjectReference Include="../UiEditorKit.Manager.Core/UiEditorKit.Manager.Core.csproj" />
    <ProjectReference Include="../UiEditorKit.Manager.Infrastructure/UiEditorKit.Manager.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../package/current/**/*"><Link>packages/current/%(RecursiveDir)%(Filename)%(Extension)</Link><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory><CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory></Content>
  </ItemGroup>
</Project>
