using System.Text.Json;
using UiEditorKit.Manager.Core;
using UiEditorKit.Manager.Domain;
using UiEditorKit.Manager.Infrastructure;

namespace UiEditorKit.Manager.Tests;

[TestClass]
public sealed class ManagerTests
{
    private string root = null!;
    private ManagerPaths paths = null!;

    [TestInitialize] public void Initialize() { root = Path.Combine(Path.GetTempPath(), "ui-editor-manager-tests", Guid.NewGuid().ToString("N")); paths = ManagerPaths.ForRoot(Path.Combine(root, "manager")); paths.Ensure(); }
    [TestCleanup] public void Cleanup() { if (Directory.Exists(root)) Directory.Delete(root, true); }

    [TestMethod] public void Manager_paths_are_centralized() { Assert.StartsWith(Path.GetFullPath(root), paths.Root); Assert.Contains(Path.Combine("manager", "data"), paths.Data); }
    [TestMethod] [DataRow("../escape")] [DataRow("/absolute")] [DataRow("C:\\absolute")] [DataRow("a/../../b")] public void Unsafe_relative_paths_are_rejected(string value) => Assert.IsFalse(ManagerPathRules.IsSafeRelativePath(value));
    [TestMethod] [DataRow(".ui-editor-kit/file.props")] [DataRow("src/App/App.csproj")] public void Safe_relative_paths_are_accepted(string value) => Assert.IsTrue(ManagerPathRules.IsSafeRelativePath(value));
    [TestMethod] public void Resolve_inside_blocks_traversal() => Assert.Throws<InvalidOperationException>(() => ManagerPathRules.ResolveInside(root, "../escape"));
    [TestMethod] public void Root_drive_is_rejected() { var result = new TargetAppInspector(paths).CheckAsync(Path.GetPathRoot(root)!).Result; Assert.AreEqual(ManagerErrorCodes.TargetPathUnsafe, result.Code); }
    [TestMethod] public async Task Missing_manifest_requires_M79() { var target = Directory.CreateDirectory(Path.Combine(root, "legacy")).FullName; var result = await new TargetAppInspector(paths).CheckAsync(target); Assert.AreEqual(ManagerErrorCodes.TargetNotM78Compatible, result.Code); Assert.Contains("M79", result.Message); }
    [TestMethod] public async Task Invalid_manifest_is_rejected() { var target = Directory.CreateDirectory(Path.Combine(root, "bad")).FullName; await File.WriteAllTextAsync(Path.Combine(target, "ui-editor-target.json"), "{}"); var result = await new TargetAppInspector(paths).CheckAsync(target); Assert.AreEqual(ManagerErrorCodes.TargetManifestInvalid, result.Code); }
    [TestMethod] public void Contract_rejects_unsupported_mode_and_version() { var manifest = Manifest() with { IntegrationMode = "heuristic", SupportedEditorContractVersion = "9" }; var errors = TargetContractValidator.Validate(manifest); Assert.HasCount(2, errors); }
    [TestMethod] public async Task Prepared_target_and_project_selection_are_accepted() { var target = await CreateTargetAsync(); var inspector = new TargetAppInspector(paths); Assert.IsTrue((await inspector.CheckAsync(target)).Success); Assert.IsTrue((await inspector.CheckAsync(Path.Combine(target, "App.csproj"))).Success); }
    [TestMethod] public async Task Write_probe_leaves_no_file() { var target = await CreateTargetAsync(); await new TargetAppInspector(paths).CheckAsync(target); Assert.IsFalse(Directory.EnumerateFiles(target, "*.tmp", SearchOption.AllDirectories).Any()); }
    [TestMethod] public async Task Corrupt_known_apps_store_does_not_crash() { await File.WriteAllTextAsync(Path.Combine(paths.Data, "known-target-apps.json"), "broken"); Assert.HasCount(0, (await new KnownTargetAppsStore(paths).LoadAsync()).Apps); }
    [TestMethod] public async Task Known_apps_store_is_versioned_deduplicated_and_atomic() { var store = new KnownTargetAppsStore(paths); var app = Known(); await store.UpsertAsync(app); await store.UpsertAsync(app with { DisplayName = "Neu" }); var doc = await store.LoadAsync(); Assert.AreEqual(1, doc.SchemaVersion); Assert.HasCount(1, doc.Apps); Assert.IsFalse(Directory.EnumerateFiles(paths.Data, "*.tmp").Any()); }
    [TestMethod] public async Task Package_integrity_is_verified() { var package = await CreatePackageAsync("1.0", "eins"); Assert.IsTrue((await new LocalPackageCatalog(package).LoadAsync()).Result.Success); await File.WriteAllTextAsync(Path.Combine(package, "files", "payload.txt"), "manipuliert"); Assert.AreEqual(ManagerErrorCodes.PackageIntegrityFailed, (await new LocalPackageCatalog(package).LoadAsync()).Result.Code); }
    [TestMethod] public void Plan_is_deterministic_and_foreign_file_conflicts() { var package = Package("hash"); var manifest = Manifest(); var hashes = new Dictionary<string, string> { [".ui-editor-kit/payload.txt"] = "foreign" }; var a = InstallationPlanner.Create(manifest, root, package, hashes, null, DateTimeOffset.UtcNow); var b = InstallationPlanner.Create(manifest, root, package, hashes, null, DateTimeOffset.UtcNow.AddHours(1)); Assert.AreEqual(a.PreviewId, b.PreviewId); Assert.AreEqual(InstallationAction.Conflict, a.Files.Single().Action); }
    [TestMethod] public async Task Installation_requires_confirmation_and_writes_owned_manifest() { var setup = await SetupServiceAsync("1.0", "eins"); var preview = await setup.Service.PreviewAsync(setup.Target); Assert.IsFalse((await setup.Service.ExecuteAsync(preview.Plan!, false)).Success); var result = await setup.Service.ExecuteAsync(preview.Plan!, true); Assert.IsTrue(result.Success); var state = await new TargetAppInspector(paths).LoadInstallationAsync(setup.Target); Assert.AreEqual("1.0", state!.InstalledPackageVersion); Assert.HasCount(1, state.Files); Assert.AreEqual(await Hashing.FileAsync(Path.Combine(setup.Target, ".ui-editor-kit", "payload.txt")), state.Files[0].InstalledHash); }
    [TestMethod] public async Task Stale_preview_is_rejected() { var setup = await SetupServiceAsync("1.0", "eins"); var preview = await setup.Service.PreviewAsync(setup.Target); await File.WriteAllTextAsync(Path.Combine(setup.Target, ".ui-editor-kit", "payload.txt"), "foreign"); Assert.AreEqual(ManagerErrorCodes.InstallPreviewStale, (await setup.Service.ExecuteAsync(preview.Plan!, true)).Code); }
    [TestMethod] public async Task Install_failure_rolls_back_and_keeps_foreign_file() { var setup = await SetupServiceAsync("1.0", "eins"); var foreign = Path.Combine(setup.Target, "foreign.txt"); await File.WriteAllTextAsync(foreign, "schutz"); var hash = await Hashing.FileAsync(foreign); var preview = await setup.Service.PreviewAsync(setup.Target); var result = await setup.Service.ExecuteAsync(preview.Plan!, true, new ThrowingFault()); Assert.IsFalse(result.Success); Assert.IsTrue(result.RollbackSucceeded); Assert.IsFalse(File.Exists(Path.Combine(setup.Target, ".ui-editor-kit", "payload.txt"))); Assert.AreEqual(hash, await Hashing.FileAsync(foreign)); }
    [TestMethod] public async Task Install_is_idempotent_update_is_owned_and_version_changes() { var setup = await SetupServiceAsync("1.0", "eins"); var first = await setup.Service.PreviewAsync(setup.Target); Assert.IsTrue((await setup.Service.ExecuteAsync(first.Plan!, true)).Success); Assert.AreEqual(InstallationAction.Unchanged, (await setup.Service.PreviewAsync(setup.Target)).Plan!.Files.Single().Action); await WritePackageAsync(setup.PackageRoot, "2.0", "zwei"); var update = await setup.Service.PreviewAsync(setup.Target); Assert.AreEqual(InstallationAction.Update, update.Plan!.Files.Single().Action); Assert.IsTrue((await setup.Service.ExecuteAsync(update.Plan, true)).Success); Assert.AreEqual("2.0", (await new TargetAppInspector(paths).LoadInstallationAsync(setup.Target))!.InstalledPackageVersion); }
    [TestMethod] public async Task Local_change_blocks_update_and_uninstall() { var setup = await SetupServiceAsync("1.0", "eins"); var install = await setup.Service.PreviewAsync(setup.Target); await setup.Service.ExecuteAsync(install.Plan!, true); await File.WriteAllTextAsync(Path.Combine(setup.Target, ".ui-editor-kit", "payload.txt"), "local"); await WritePackageAsync(setup.PackageRoot, "2.0", "zwei"); Assert.IsFalse((await setup.Service.PreviewAsync(setup.Target)).Plan!.CanExecute); Assert.IsFalse((await setup.Service.UninstallPreviewAsync(setup.Target)).Plan!.CanExecute); }
    [TestMethod] public async Task Uninstall_removes_only_owned_files_and_preserves_profiles() { var setup = await SetupServiceAsync("1.0", "eins"); var profile = Path.Combine(setup.Target, "profiles", "ui.json"); Directory.CreateDirectory(Path.GetDirectoryName(profile)!); await File.WriteAllTextAsync(profile, "layout"); var install = await setup.Service.PreviewAsync(setup.Target); await setup.Service.ExecuteAsync(install.Plan!, true); var preview = await setup.Service.UninstallPreviewAsync(setup.Target); Assert.IsTrue((await setup.Service.UninstallAsync(preview.Plan!, true)).Success); Assert.IsTrue(File.Exists(profile)); Assert.IsFalse(File.Exists(Path.Combine(setup.Target, ".ui-editor-kit", "payload.txt"))); }
    [TestMethod] public async Task Structured_log_contains_action_but_no_domain_values() { var log = new ManagerLogger(paths); await log.WriteAsync(new(DateTimeOffset.UtcNow, ManagerOperation.Install, "app.id", root, true, "ok", "tx", "1", 2)); var item = (await log.ReadAsync()).Single(); Assert.AreEqual(ManagerOperation.Install, item.Action); Assert.AreEqual(2, item.AffectedFileCount); }
    [TestMethod] public void Domain_assembly_has_no_WPF_IO_or_process_dependencies() { var refs = typeof(InstallationPlan).Assembly.GetReferencedAssemblies().Select(a => a.Name).ToArray(); CollectionAssert.DoesNotContain(refs, "PresentationFramework"); CollectionAssert.DoesNotContain(refs, "System.Diagnostics.Process"); }

    private async Task<(string Target, string PackageRoot, TargetInstallationService Service)> SetupServiceAsync(string version, string content) { var target = await CreateTargetAsync(); var package = await CreatePackageAsync(version, content); return (target, package, new(paths, new(paths), new(package))); }
    private async Task<string> CreateTargetAsync() { var target = Directory.CreateDirectory(Path.Combine(root, "target")).FullName; await File.WriteAllTextAsync(Path.Combine(target, "App.csproj"), "<Project />"); await File.WriteAllTextAsync(Path.Combine(target, "ui-editor-target.json"), JsonSerializer.Serialize(Manifest(), JsonOptions)); return target; }
    private async Task<string> CreatePackageAsync(string version, string content) { var package = Directory.CreateDirectory(Path.Combine(root, "package")).FullName; await WritePackageAsync(package, version, content); return package; }
    private static async Task WritePackageAsync(string package, string version, string content) { Directory.CreateDirectory(Path.Combine(package, "files")); var source = Path.Combine(package, "files", "payload.txt"); await File.WriteAllTextAsync(source, content); var hash = await Hashing.FileAsync(source); await File.WriteAllTextAsync(Path.Combine(package, "package.json"), JsonSerializer.Serialize(new IntegrationPackage(1, version, "1.0", [new(".ui-editor-kit/payload.txt", "files/payload.txt", hash, "copy")]), JsonOptions)); }
    private static IntegrationPackage Package(string hash) => new(1, "1", "1.0", [new(".ui-editor-kit/payload.txt", "files/payload.txt", hash, "copy")]);
    private static TargetAppManifest Manifest() => new(1, "test.prepared.app", "Test App", "wpf-net10", "App.csproj", "net10.0-windows", "prepared-native-editor", ".ui-editor-kit", "App.csproj", "App.csproj", "1.0", new(true, true, true, true, true), [".ui-editor-kit/payload.txt", ".ui-editor-kit/installation.json"], new("dotnetProject", "App.csproj", null, []), new("dotnetProject", "App.csproj", null, []), "owner");
    private KnownTargetApp Known() => new("test.prepared.app", "Test", root, "App.csproj", "ui-editor-target.json", "1.0", TargetContractStatus.ReadyToInstall, null, DateTimeOffset.UtcNow, null, null);
    private static JsonSerializerOptions JsonOptions => new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
    private sealed class ThrowingFault : IManagerFaultInjector { public void BeforeFileWrite(int index, string relativePath) => throw new InvalidOperationException("diagnostic fault"); }
}
